import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator
from numpy.random import random
import pandas as pd
import random as rand
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import visuals as vs
import math

class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """ 

    def __init__(self, env, learning=False, epsilon=1.0, alpha=0.5, epsilon_decay='linear'):
        super(LearningAgent, self).__init__(env)     # Set the agent in the evironment 
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning # Whether the agent is expected to learn
        self.Q = dict()          # Create a Q-table which will be a dictionary of tuples
        self.epsilon = epsilon   # Random exploration factor
        self.alpha = alpha       # Learning factor

        ###########
        ## DONE ##
        ###########
        # Set any additional class parameters as needed
        self.epsilon_decay = epsilon_decay
        self.trail_number = 0

    def reset(self, destination=None, testing=False):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        # Select the destination as the new location to route to
        self.planner.route_to(destination)
        
        ########### 
        ##  DONE ##
        ###########
        # Update epsilon using a decay function of your choice
        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        self.trail_number +=1
        if not testing:
            if self.epsilon_decay == 'linear':
                self.epsilon = self.epsilon - 0.05
            elif self.epsilon_decay == 'a**t':
                self.epsilon = 0.9**(0.15*self.trail_number)
            elif self.epsilon_decay == '1/t**2': 
                self.epsilon = 1/self.trail_number**2
            elif self.epsilon_decay == 'cos(at)': 
                self.epsilon = math.cos(self.trail_number)       
        else:
            self.epsilon = 0
            self.alpha = 0
        
        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        # Collect data about the environment
        waypoint = self.planner.next_waypoint() # The next waypoint 
        inputs = self.env.sense(self)           # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)  # Remaining deadline
        
        ########### 
        ## DONE ##
        ###########
        # Set 'state' as a tuple of relevant data for the agent        
        state = (waypoint, inputs['light'], inputs['left'], inputs['oncoming'])

        return state


    def get_maxQ(self, state):
        """ The get_max_Q function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        ########### 
        ## DONE  ##
        ###########
        # Calculate the maximum Q-value of all actions for a given state

        maxQ = self.Q[state][max(self.Q[state], key=self.Q[state].get)]

        return maxQ 


    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        ########### 
        ## DONE ##
        ###########
        # When learning, check if the 'state' is not in the Q-table
        # If it is not, create a new dictionary for that state
        #   Then, for each action available, set the initial Q-value to 0.0
        
        if self.learning:
            if state not in self.Q:
                self.Q[state] = {None:0.0, 'forward': 0.0, 'left':0.0, 'right':0.0}
                
        return


    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()
        action = rand.choice(self.valid_actions)
        
        ########### 
        ## DONE ##
        ###########
        # When not learning, choose a random action
        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state
        if self.learning :
            if self.epsilon > random():
                action = rand.choice(self.valid_actions)
            else:
               max_Q = self.get_maxQ(state) 
               print self.Q[state]
               action = rand.choice([key for key,value in self.Q[state].iteritems() if value == max_Q])    
        
        return action


    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """

        ########### 
        ## DONE ##
        ###########
        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')
        if self.learning:
            self.Q[state][action] = (1-self.alpha)*self.Q[state][action] + \
                                    self.alpha*(reward)
        return


    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()          # Get current state
        self.createQ(state)                 # Create 'state' in Q-table
        action = self.choose_action(state)  # Choose an action
        reward = self.env.act(self, action) # Receive a reward
        self.learn(state, action, reward)   # Q-learn

        return
        

def run(epsilon_decay, alpha, n_test, tolerance,optimized,n_train=20):
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment()
    
    ##############
    # Create the driving agent
    # Flags:
    #   learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha   - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent, learning=True, alpha= alpha, epsilon_decay=epsilon_decay)
    
    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent,  enforce_deadline=True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    sim = Simulator(env, update_delay=0.01, log_metrics=True, optimized=optimized)
    
    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    sim.run(n_test=n_test, tolerance= tolerance, n_train=n_train)


if __name__ == '__main__':
    
	#default learning
    run('linear', 0.5, 10, 0.05, False)

    #optimised learning
    epsilon_decay_params = [ 'a**t', '1/t**2', 'cos(at)', 'linear']
    learning_params = [ 0.5, 0.6]
    n_test_params = [15, 10]
    tolerance_params = [0.05, 0.2]
    optimized=True
    optimized_results = []
    n_train = 150

    test_for_optimality = False
    if test_for_optimality:
        for epsilon_decay in epsilon_decay_params:
            for alpha in learning_params:
                for n_test in n_test_params:
                    for tolerance in tolerance_params:
                        run(epsilon_decay, alpha, n_test, tolerance, optimized, n_train)
                        safety_rating, reliability_rating = vs.output_results('sim_improved-learning.csv')
                        optimized_results.append({'safety':safety_rating, 'reliability':reliability_rating, 'params':(epsilon_decay,alpha, n_test, tolerance)})
        print optimized_results
        
    #run('a**t', 0.5, 30, 0.2, True, n_train)
                    	